name: 'Compile versions'

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  pull-requests: 'write'

defaults:
  run:
    shell: 'bash'

jobs:
  compile-versions:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Get versions list'
        run: |-
          mkdir -p ./data
          go run ./cmd/compile-versions/main.go > ./data/versions.json

          echo "Computed versions:"
          cat ./data/versions.json

      - name: 'Create/Update Pull Request'
        uses: 'abcxyz/pkg/.github/actions/create-pull-request@main' # ratchet:exclude
        with:
          token: '${{ secrets.ACTIONS_BOT_TOKEN }}'
          base_branch: '${{ github.ref_name }}'
          head_branch: 'actions/compile-versions-${{ github.ref_name }}'
          title: 'Update gcloud versions'
          body: 'Update latest gcloud versions'
          compute_paths: true
