name: 'Release'

on:
  push:
    branches:
      - 'main'
      - 'release/**/*'

jobs:
  release:
    # TODO(sethvargo): revert to a tag when ready
    uses: 'google-github-actions/.github/.github/workflows/release.yml@main' # ratchet:exclude
    secrets:
      ACTIONS_BOT_TOKEN: '${{ secrets.ACTIONS_BOT_TOKEN }}'

  publish:
    needs:
      - 'release'
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: 'actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a' # ratchet:actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://wombat-dressing-room.appspot.com/'

      - env:
          NODE_AUTH_TOKEN: '${{ secrets.NODE_AUTH_TOKEN }}'
        run: |-
          npm publish --provenance --access public
