name: 'Unit'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'ubuntu-latest'
        - 'windows-2019'
        - 'windows-2022'
        - 'macos-latest'
        node:
        - '16.x'
    runs-on: '${{ matrix.os }}'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-node@v3'
      with:
        node-version: '${{ matrix.node }}'

    - name: 'npm build'
      run: 'npm ci && npm run build'

    - name: 'npm lint'
      # There's no need to run the linter for each operating system, since it
      # will find the same thing 9x and clog up the PR review.
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: 'npm run lint'

    - name: 'npm test'
      env:
        KEY: '${{ secrets.SETUP_SDK_CRED_SA_KEY_JSON }}'
        B64_KEY: '${{ secrets.SETUP_SDK_CRED_SA_KEY_B64 }}'
        PROJECT_ID: '${{ secrets.SETUP_SDK_CRED_PROJECT_ID }}'
      run: 'npm run test'
